import ROUTE_MAP from './routeMap';

const routes = [
  {
    path: ROUTE_MAP.HOME,
    redirect: ROUTE_MAP.AI_LM,
  },
  {
    name: '首页',
    path: '/',
    icon: 'Home',
    component: './Home',
    hideInBreadcrumb: false,
    hideInMenu: false,
    access: 'canSeeUser',
    wrappers: ['@/wrappers/auth'],
  },
  {
    name: '模型广场',
    path: ROUTE_MAP.AI_LM,
    icon: 'Robot',
    component: '@/layouts/LmLayout',
    hideInBreadcrumb: false,
    hideInMenu: false,
    access: 'canSeeUser',
    wrappers: ['@/wrappers/auth'],
    routes: [
      {
        name: '模型列表',
        path: ROUTE_MAP.AI_LM_LIST,
        icon: 'Robot',
        component: './AILm/AILmList',
        hideInBreadcrumb: false,
        hideInMenu: true,
        access: 'canSeeUser',
        wrappers: ['@/wrappers/auth'],
      },
      {
        name: 'AI对话',
        path: ROUTE_MAP.AI_LM_CHAT,
        icon: 'Message',
        component: './AILm/AILmChat',
        hideInMenu: true,
        hideInBreadcrumb: false,
        // // 不展示菜单
        // menuRender: false,
        // // 不使用父模板
        // layout: false,
        access: 'canSeeUser',
        wrappers: ['@/wrappers/auth'],
      },
      {
        name: '对话补全',
        path: ROUTE_MAP.AI_LM_GENERATE,
        icon: 'Comment',
        component: './AILm/AILmGenerate',
        hideInMenu: true,
        hideInBreadcrumb: false,
        // // 不展示菜单
        // menuRender: false,
        // // 不使用父模板
        // layout: false,
        access: 'canSeeUser',
        wrappers: ['@/wrappers/auth'],
      },
      {
        name: '图片生成',
        path: ROUTE_MAP.AI_LM_IMAGE,
        icon: 'FileImage',
        component: './AILm/AILmImage',
        hideInMenu: true,
        hideInBreadcrumb: false,
        // // 不展示菜单
        // menuRender: false,
        // // 不使用父模板
        // layout: false,
        access: 'canSeeUser',
        wrappers: ['@/wrappers/auth'],
      },
      {
        name: '嵌入向量',
        path: ROUTE_MAP.AI_LM_EMBED,
        icon: 'Database',
        component: './AILm/AILmEmbed',
        hideInMenu: true,
        hideInBreadcrumb: false,
        // // 不展示菜单
        // menuRender: false,
        // // 不使用父模板
        // layout: false,
        access: 'canSeeUser',
        wrappers: ['@/wrappers/auth'],
      },
    ],
  },
  {
    name: '知识图谱',
    path: ROUTE_MAP.AI_GRAPH,
    icon: 'Branches',
    component: '@/layouts/GraphLayout',
    hideInMenu: false,
    hideInBreadcrumb: false,
    access: 'canSeeUser',
    wrappers: ['@/wrappers/auth'],
    routes: [
      {
        name: '图谱列表',
        path: ROUTE_MAP.AI_GRAPH_LIST,
        icon: 'Branches',
        component: './AIGraph/AIGraphList',
        hideInMenu: true,
        hideInBreadcrumb: false,
        access: 'canSeeUser',
        wrappers: ['@/wrappers/auth'],
      },
      {
        name: '图谱表格',
        path: ROUTE_MAP.AI_GRAPH_TABLE,
        icon: 'Table',
        component: './AIGraph/AIGraphTable',
        hideInMenu: true,
        hideInBreadcrumb: false,
        // layout: false,
        access: 'canSeeUser',
        wrappers: ['@/wrappers/auth'],
      },
      {
        name: '图谱展示',
        path: ROUTE_MAP.AI_GRAPH_SHOW,
        icon: 'Branches',
        component: './AIGraph/AIGraphShow',
        hideInMenu: true,
        hideInBreadcrumb: false,
        // layout: false,
        access: 'canSeeUser',
        wrappers: ['@/wrappers/auth'],
      },
      {
        name: '图谱对话',
        path: ROUTE_MAP.AI_GRAPH_CHAT,
        icon: 'Book',
        component: './AIGraph/AIGraphChat',
        hideInMenu: true,
        hideInBreadcrumb: false,
        // // 不展示菜单
        // menuRender: false,
        // // 不使用父模板
        // layout: false,
        access: 'canSeeUser',
        wrappers: ['@/wrappers/auth'],
      },
      {
        name: '文档列表',
        path: ROUTE_MAP.AI_DOCUMENT,
        icon: 'FolderOpen',
        component: './AIDocument/AIDocumentList',
        hideInMenu: true,
        hideInBreadcrumb: false,
        // // 不展示菜单
        // menuRender: false,
        // // 不使用父模板
        // layout: true,
        access: 'canSeeUser',
        wrappers: ['@/wrappers/auth'],
      },
      {
        name: '文档详情',
        path: ROUTE_MAP.AI_DOCUMENT_DETAIL,
        icon: 'FileText',
        component: './AIDocument/AIDocumentDetail',
        hideInMenu: true,
        hideInBreadcrumb: false,
        // // 不展示菜单
        // menuRender: false,
        // // 不使用父模板
        // layout: false,
        access: 'canSeeUser',
        wrappers: ['@/wrappers/auth'],
      },
    ],
  },
  // {
  //   name: '模型列表',
  //   icon: 'Code',
  //   path: ROUTE_MAP.AI_LM_LIST,
  //   component: './AILm/AILmList',
  //   hideInMenu: false,
  //   access: 'canSeeAdmin',
  //   wrappers: ['@/wrappers/auth'],
  // },
  // {
  //   name: '图谱管理',
  //   path: ROUTE_MAP.AI_GRAPH_MANAGE,
  //   icon: 'DiffOutlined',
  //   component: './AIGraph/AIGraphWorkspace',
  //   hideInMenu: false,
  //   access: 'canSeeAdmin',
  //   wrappers: ['@/wrappers/auth'],
  // },
  // {
  //   name: '模型管理',
  //   path: ROUTE_MAP.AI_LM_MANAGE,
  //   icon: 'AppstoreAddOutlined',
  //   component: './AILm/AILmManage',
  //   hideInMenu: false,
  //   access: 'canSeeAdmin',
  //   wrappers: ['@/wrappers/auth'],
  // },
  {
    name: '系统配置',
    path: ROUTE_MAP.AI_PLATFORM_LIST,
    icon: 'Apartment',
    component: './AIPlatform/AIPlatformList',
    access: 'canSeeAdmin',
    wrappers: ['@/wrappers/auth'],
  },
  // {
  //   name: '模型管理',
  //   path: ROUTE_MAP.AI_LM,
  //   icon: 'Code',
  //   access: 'canSeeAdmin',
  //   hideInBreadcrumb: true,
  //   wrappers: ['@/wrappers/auth'],
  //   routes: [
  //     {
  //       name: '模型管理（卡片）',
  //       icon: 'UnorderedList',
  //       path: ROUTE_MAP.AI_LM_MANAGE,
  //       component: './AILm/AILmManage',
  //       hideInMenu: false,
  //       access: 'canSeeAdmin',
  //       wrappers: ['@/wrappers/auth'],
  //     },
  //     {
  //       name: '模型管理（表单）',
  //       icon: 'OrderedList',
  //       path: ROUTE_MAP.AI_LM_LIST,
  //       component: './AILm/AILmList',
  //       hideInMenu: false,
  //       access: 'canSeeAdmin',
  //       wrappers: ['@/wrappers/auth'],
  //     },
  //   ],
  // },
  // {
  //   name: '系统配置',
  //   path: ROUTE_MAP.AI_PLATFORM,
  //   icon: 'Apartment',
  //   access: 'canSeeAdmin',
  //   wrappers: ['@/wrappers/auth'],
  //   routes: [
  //     {
  //       name: '系统配置（表单）',
  //       path: ROUTE_MAP.AI_PLATFORM_LIST,
  //       icon: 'OrderedList',
  //       component: './AIPlatform/AIPlatformList',
  //       access: 'canSeeAdmin',
  //       wrappers: ['@/wrappers/auth'],
  //     },
  //   ],
  // },
  {
    name: '用户管理',
    path: ROUTE_MAP.USER_MANAGE,
    icon: 'User',
    component: './Users',
    access: 'canSeeAdmin',
    wrappers: ['@/wrappers/auth'],
  },
  {
    name: '角色管理',
    path: ROUTE_MAP.ROLE_MANAGE,
    icon: 'Team',
    component: './Roles',
    access: 'canSeeAdmin',
    wrappers: ['@/wrappers/auth'],
  },
  {
    name: '密码修改',
    path: ROUTE_MAP.PWD_CHANGE,
    component: './PwdChange',
    hideInMenu: true,
    access: 'canSeeUser',
    wrappers: ['@/wrappers/auth'],
  },
  {
    name: '初始化',
    path: ROUTE_MAP.SETUP,
    component: './Setup',
    layout: false,
    hideInMenu: true,
    wrappers: ['@/wrappers/auth'],
  },
  {
    name: '登录',
    path: ROUTE_MAP.LOGIN,
    component: './Login',
    layout: false,
    hideInMenu: true,
    wrappers: ['@/wrappers/auth'],
  },
  {
    name: '注册',
    path: ROUTE_MAP.REGISTER,
    component: './Register',
    layout: false,
    hideInMenu: true,
    wrappers: ['@/wrappers/auth'],
  },
  {
    name: '用户协议',
    path: ROUTE_MAP.AGREEMENT,
    component: './Agreement',
    layout: false,
    hideInMenu: true,
  },
  {
    path: '/*',
    component: './404',
    layout: false,
    hideInMenu: true,
    wrappers: ['@/wrappers/auth'],
  },
];

export default routes;
