enum ROUTE_MAP {
  BASE = '/',
  HOME = '/home',
  LOGIN = '/login',
  SETUP = '/setup',
  REGISTER = '/register',
  AGREEMENT = '/agreement',
  PWD_CHANGE = '/pwdchange',
  USER_MANAGE = '/user/manage',
  ROLE_MANAGE = '/role/manage',
  AI_LM = '/ai/lm',
  AI_LM_LIST = '/ai/lm/:platform',
  AI_LM_CHAT = '/ai/lm/:platform/model/:model/chat',
  AI_LM_GENERATE = '/ai/lm/:platform/model/:model/generate',
  AI_LM_IMAGE = '/ai/lm/:platform/model/:model/image',
  AI_LM_EMBED = '/ai/lm/:platform/model/:model/embed',
  AI_PLATFORM = '/ai/platform',
  AI_PLATFORM_MANAGE = '/ai/platform/manage',
  AI_PLATFORM_LIST = '/ai/platform/list',
  AI_GRAPH = '/ai/graph',
  AI_GRAPH_LIST = '/ai/graph/:graph',
  AI_GRAPH_TABLE = '/ai/graph/:graph/workspace/:workspace/table',
  AI_GRAPH_SHOW = '/ai/graph/:graph/workspace/:workspace/show',
  AI_GRAPH_CHAT = '/ai/graph/:graph/workspace/:workspace/chat',
  AI_DOCUMENT = '/ai/graph/:graph/workspace/:workspace/document',
  AI_DOCUMENT_DETAIL = '/ai/graph/:graph/workspace/:workspace/document/:document_id/detail',
  AGENT='/agent',
  AGENT_LIST='/agent/list',
  AGENT_TASK='/agent/:agent/task',
  AGENT_DETAIL='/agent/:agent/detail',
}

export default ROUTE_MAP;
